# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jabal Torres
email: info@jabaltorres.com
description: > # this means to ignore newlines until "baseurl:"
  UI / UX Designer and Front-End Developer with relentless curiosity and insatiable hunger for knowledge. I'm passionate about responsive design, elegant code, and beautiful typography.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://capitaljt.github.io" # the base hostname & protocol for your site
twitter_username: jabaltorres
github_username:  capitalJT

# Build settings
markdown: kramdown
permalink: /:title
#future: true
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: _sass
  # style: compressed